---
GENERAL:
  # cf config
  CF_API_URL: https://api.cloud.service.gov.uk
  CF_ORG: govuk-notify
  CF_SPACE: {{ CF_SPACE }}

  # general autoscaler config
  SCHEDULE_INTERVAL_SECONDS: 5
  COOLDOWN_SECONDS_AFTER_SCALE_UP: {{ COOLDOWN_SECONDS_AFTER_SCALE_UP }}
  COOLDOWN_SECONDS_AFTER_SCALE_DOWN: {{ COOLDOWN_SECONDS_AFTER_SCALE_DOWN }}
  STATSD_ENABLED: {{ STATSD_ENABLED }}

  # instance limits
  MIN_INSTANCE_COUNT_HIGH: {{ MIN_INSTANCE_COUNT_HIGH }}
  MIN_INSTANCE_COUNT_LOW: {{ MIN_INSTANCE_COUNT_LOW }}
  MAX_INSTANCE_COUNT_HIGH: {{ MAX_INSTANCE_COUNT_HIGH }}
  MAX_INSTANCE_COUNT_MEDIUM: {{ MAX_INSTANCE_COUNT_MEDIUM }}
  MAX_INSTANCE_COUNT_LOW: {{ MAX_INSTANCE_COUNT_LOW }}

SCALERS:
  AWS_REGION: eu-west-1
  SQS_QUEUE_PREFIX: {{ SQS_QUEUE_PREFIX }}
  DEFAULT_SCHEDULE_SCALE_FACTOR: {{ DEFAULT_SCHEDULE_SCALE_FACTOR }}
  SCHEDULE_SCALER_ENABLED: {{ SCHEDULE_SCALER_ENABLED }}
  DEFAULT_CPU_PERCENTAGE_THRESHOLD: {{ DEFAULT_CPU_PERCENTAGE_THRESHOLD }}

APPS:
  - name: notify-api
    min_instances: {{ MIN_INSTANCE_COUNT_HIGH }}
    max_instances: {{ MAX_INSTANCE_COUNT_HIGH }}
    scalers:
      - type: ElbScaler
        elb_name: 'notify-paas-proxy'
        threshold: 800
      - type: ScheduleScaler
        schedule:
          scale_factor: 0.6
          workdays:
            - 08:00-19:00
          weekends:
            - 09:00-17:00

  - name: notify-delivery-worker-sender
    min_instances: {{ MIN_INSTANCE_COUNT_HIGH }}
    max_instances: {{ MAX_INSTANCE_COUNT_HIGH }}
    scalers:
      - type: ScheduledJobsScaler
        threshold: 600
      - type: SqsScaler
        queues: [send-sms-tasks, send-email-tasks]
        threshold: 600
      - type: ScheduleScaler
        schedule:
          scale_factor: 0.4
          workdays:
            - 08:00-19:00
          weekends:
            - 08:00-19:00

  - name: notify-delivery-worker-jobs
    min_instances: {{ MIN_INSTANCE_COUNT_LOW }}
    max_instances: {{ MAX_INSTANCE_COUNT_HIGH }}
    scalers:
      - type: SqsScaler
        queues:  [database-tasks, job-tasks]
        threshold: 250

  - name: notify-delivery-worker-retry-tasks
    min_instances: {{ MIN_INSTANCE_COUNT_LOW }}
    max_instances: {{ MAX_INSTANCE_COUNT_LOW }}
    scalers:
      - type: SqsScaler
        queues:  [retry-tasks]
        threshold: 250

  - name: notify-delivery-worker-internal
    min_instances: {{ MIN_INSTANCE_COUNT_LOW }}
    max_instances: {{ MAX_INSTANCE_COUNT_LOW }}
    scalers:
      - type: SqsScaler
        queues:  [notify-internal-tasks]
        threshold: 250

  - name: notify-delivery-worker-letters
    min_instances: {{ MIN_INSTANCE_COUNT_LOW }}
    max_instances: {{ MAX_INSTANCE_COUNT_LOW }}
    scalers:
      - type: SqsScaler
        queues:  [create-letters-pdf-tasks, letter-tasks]
        threshold: 250

  - name: notify-delivery-worker-research
    min_instances: {{ MIN_INSTANCE_COUNT_LOW }}
    max_instances: {{ MAX_INSTANCE_COUNT_LOW }}
    scalers:
      - type: SqsScaler
        queues:  [research-mode-tasks]
        threshold: 250

  - name: notify-delivery-worker-priority
    min_instances: {{ MIN_INSTANCE_COUNT_LOW }}
    max_instances: {{ MAX_INSTANCE_COUNT_LOW }}
    scalers:
      - type: SqsScaler
        queues:  [priority-tasks]
        threshold: 250

  - name: notify-delivery-worker-periodic
    min_instances: {{ MIN_INSTANCE_COUNT_LOW }}
    max_instances: {{ MAX_INSTANCE_COUNT_LOW }}
    scalers:
      - type: SqsScaler
        queues:  [periodic-tasks]
        threshold: 250

  - name: notify-delivery-worker-reporting
    min_instances: {{ MIN_INSTANCE_COUNT_LOW }}
    max_instances: {{ MAX_INSTANCE_COUNT_LOW }}
    scalers:
      - type: SqsScaler
        queues:  [reporting-tasks]
        threshold: 250

  - name: notify-delivery-worker-receipts
    min_instances: {{ MIN_INSTANCE_COUNT_LOW }}
    max_instances: {{ MAX_INSTANCE_COUNT_HIGH }}
    scalers:
      - type: SqsScaler
        queues:  [ses-callbacks]
        threshold: 250
      - type: ScheduleScaler
        schedule:
          scale_factor: 0.3
          workdays:
            - 08:00-19:00
          weekends:
            - 08:00-19:00

  - name: notify-template-preview
    min_instances: {{ MIN_INSTANCE_COUNT_TEMPLATE_PREVIEW }}
    max_instances: {{ MAX_INSTANCE_COUNT_TEMPLATE_PREVIEW }}
    scalers:
      - type: ScheduledJobsScaler
        threshold: 8
      - type: SqsScaler
        queues:  [create-letters-pdf-tasks, letter-tasks, retry-tasks]
        threshold: 8
      - type: ScheduleScaler
        schedule:
          scale_factor: 0.4
          workdays:
            - 08:00-19:00
          weekends:
            - 08:00-19:00

  - name: notify-delivery-worker-service-callbacks
    min_instances: {{ MIN_INSTANCE_COUNT_LOW }}
    max_instances: {{ MAX_INSTANCE_COUNT_LOW }}
    scalers:
      - type: ScheduledJobsScaler
        threshold: 8
      - type: SqsScaler
        queues:  [service-callbacks]
        threshold: 500

  - name: notify-antivirus
    min_instances: {{ MIN_INSTANCE_COUNT_LOW }}
    max_instances: {{ MAX_INSTANCE_COUNT_LOW }}
    scalers:
      - type: SqsScaler
        queues:  [antivirus-tasks]
        threshold: 50
